on:
  push:
    branches:
      - "*"

name: Test Across Matrix

jobs:
  test:    
    ## Defines the platform for each test run
    runs-on: 1.22.x
    
    ## the steps that will be run through for each version and platform
    ## combination
    steps:
    ## sets up go based on the version
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    ## checks out our code locally so we can work with the files
    - name: Checkout code
      uses: actions/checkout@v2
    
    ## runs go test ./...
    - name: Test
      run: go test ./...
